### ISSUE TITLE
Broken on Eager (https://eager.io)

### ISSUE THREAD

**Issue by adamschwartz** [mrmrs/cssstats#117]
- https://eager.io returns `TypeError: Cannot read property 'length' of undefined`.
- Following the suggestion to specify a file directly, `"https://eager.io/38c01695c449/app.css"` returns [incorrect results](http://cssstats.com/stats?link=https%3A%2F%2Feager.io%2F38c01695c449%2Fapp.css), suggesting there are only 3 rules, for example.
- Manually pasting the CSS into “Raw CSS” causes the site to reload with no result displayed (as if no query was made or perhaps an error handled silently).

I have a theory that it relates to SSL (particularly RC4), but very much a wild guess. Hope this helps!

**Comment by mrmrs** [comment]
@adamschwartz - it definitely helps! The more debugging info we have the better :) I'm moving all tickets that have URLs that fail over to #128. Please let us know if you find any other sites that fail to parse.
