### ISSUE TITLE
Broken on http://alistapart.com

### ISSUE THREAD

**Issue by alexkadis** [mrmrs/cssstats#119]
When looking at AListApart, I get the error, "TypeError: Cannot read property 'specificity' of undefined".

URL: http://alistapart.com/
CSS: http://alistapart.com/d/_cache/b51a994b39148d1dd3050c233146844810f5bf1d.1418848595.css

**Comment by mrmrs** [comment]
@alexkadis - Thanks for letting us know! Really helpful to have multiple sites to debug against. Let us know if you find any other URLs. As I'd like to keep track of these URLs in one place to reduce noise I'm going to close this out as I've moved the URL to #128
