### ISSUE TITLE
TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by verpixelt** [mrmrs/cssstats#123]
I get this error with nearly every site/direct link to the CSS of a site I paste into. It also spits out this error with your "popular pages".

**Comment by johnotander** [comment]
This is a bug in the https://github.com/jxnblk/css-statistics module that has been patched but not yet published. When the latest version is published, hopefully today, this will be fixed. If you happen to be running the app locally, you can change the `package.json` to point at the repo as a temporary fix.

cc/ @jxnblk
