### ISSUE TITLE
Add support for @import

### ISSUE THREAD

**Issue by delan** [mrmrs/cssstats#83]
Currently `@import` statements are not followed, so if all of the CSS directly reachable from a page are `@import` statements, then all of the statistics are zero.

Support would be greatly appreciated :)

Test case: http://cssstats.com/stats?url=https%3A%2F%2Fwww.azabani.com%2F

**Comment by johnotander** [comment]
This issue is now fixed with the latest version of [`get-css`](https://github.com/jxnblk/get-css) so I believe all that's needed is `npm i --save get-css` and redeploying.

cc @mrmrs

**Comment by mrmrs** [comment]
@johnotander - sorry forgot to comment - ran that command and redeployed last night

**Comment by johnotander** [comment]
Awesome! It works!
